version: "2.0.0"
name: Teste CouchDB Multi-VM
caliper:
  blockchain: fabric

channels:
  - channelName: mychannel
    contracts:
    - id: testecouch

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
      - name: 'Admin'
        clientPrivateKey:
          path: "../fabric-network/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk"
        clientSignedCert:
          path: "../fabric-network/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem"
    connectionProfile:
      path: "./connection-profile-org1.yaml" # Usaremos um perfil de conexão para manter organizado
      discover: false # Desabilitamos o discover, pois definiremos tudo manualmente

  - mspid: Org2MSP
    identities:
      certificates:
      - name: 'Admin'
        clientPrivateKey:
          path: "../fabric-network/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/priv_sk"
        clientSignedCert:
          path: "../fabric-network/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem"
    connectionProfile:
      path: "./connection-profile-org1.yaml" # Ambas as orgs podem usar o mesmo mapa da rede
      discover: false
